cutlink/models/__init__.py
from datetime import datetime
from cutlink.extentions import db 
from cutlink.utils.time import add_time_from_now
from flask_authorize import PermissionsMixin

from .auth import User




class Link(db.Model,PermissionsMixin):
    __tablename__= "links"
    __permissions__ = dict(
        owner=['read', 'update', 'delete', 'revoke'],
        group=['read', 'update'],
        other=['read']
    )

    id = db.Column(db.Integer()  , primary_key=True,unique=True)

    code = db.Column(db.String(8),    nullable=False , unique=True)
    target = db.Column(db.String(1024), nullable=False , unique=False)

    created_at = db.Column(db.DateTime, nullable=True, default=datetime.utcnow)
    expire_at = db.Column(db.DateTime, nullable=True, default=add_time_from_now)

    counter = db.Column(db.Integer()  , default=0)
    max_clicked = db.Column(db.Integer()  , default=-1)

    def __repr__(self):
        return f"Link('{self.code}', '{self.expire_at}', '{self.counter}')"

cutlink/models/auth.py
from cutlink.extentions import db
from flask_authorize import RestrictionsMixin, AllowancesMixin
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

# mapping tables
UserGroup = db.Table(
    'user_group', db.Model.metadata,
    db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
    db.Column('group_id', db.Integer, db.ForeignKey('groups.id'))
)


UserRole = db.Table(
    'user_role', db.Model.metadata,
    db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('roles.id'))
)



class User(db.Model,UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)

    # `roles` and `groups` are reserved words that *must* be defined
    # on the `User` model to use group- or role-based authorization.
    roles = db.relationship('Role', secondary=UserRole)
    groups = db.relationship('Group', secondary=UserGroup)


    @property
    def password(self):
        raise AttributeError('Password is not readable attribute')

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)
    
    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

from cutlink.extentions import login
@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class UserQuery(object):
    @staticmethod
    def get_user_id_by_email_or_username(email=None, username=None):
        user = User.query.filter((User.email == email) | (User.username == username)).first()
        return user.id if hasattr(user, 'id') else None  
    
    @staticmethod
    def get_user(username_email=None):
        user = User.query.filter((User.email == username_email) | (User.username == username_email)).first()
        return user.id if hasattr(user, 'id') else None  



class Group(db.Model, RestrictionsMixin):
    __tablename__ = 'groups'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)

class Role(db.Model, AllowancesMixin):
    __tablename__ = 'roles'
    __allowances__ = '*'
    __restrictions__ = {}

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)

cutlink/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,IntegerField,SelectField
from wtforms.validators import DataRequired,url,length


class GenerateShortLink(FlaskForm):
    link = StringField('Target Link (http[s]):',validators=[DataRequired(),url(),length(max=1024)],)
    expire = IntegerField('Number of use link to Expire:',default=-1)
    expire_at = SelectField('Expile age of link:',choices=((("1",'10 minutes'),("2",'30 minutes'),("3",'1 day'),("4",'1 week'))),default="1")

    submit = SubmitField('generate')

cutlink/__init__.py
from flask import Flask
from .config import config
from .extentions import db,dbug,cors,migrate,api,csrf,bootstrap,authorize,login
from .models import User

def create_app(config_name='default'):
    app = Flask(__name__)  
    app.config.from_object(config[config_name])
    
    db.init_app(app)
    dbug.init_app(app)
    cors.init_app(app)
    csrf.init_app(app)
    bootstrap.init_app(app)
    login.init_app(app)
    authorize.init_app(app)



    migrate.init_app(app,db)

    from .auth.routes import main as auth_bp
    from .main.routes import main as app_bp
    # from .apis import init_resourcess

    # init_resourcess()
    # api.init_app(app)
    app.register_blueprint(app_bp)
    app.register_blueprint(auth_bp,url_prefix='/auth')



    
    return app

    

cutlink/main/routes.py
from flask import Blueprint,render_template,request,current_app,send_from_directory,redirect
import os
from cutlink.extentions import db,login,authorize
from cutlink.models import Link,User
from cutlink.utils.generate import generate_code
from datetime import datetime
from cutlink.utils.time import add_time_from_now
from .forms import GenerateShortLink
from flask import jsonify
import flask_login

time_expire = {'1':10,'2':20,'3':24*60,'4':24*60*7}

main = Blueprint('main',__name__)

@main.route("/",methods=['GET','POST'])
def index():
    form = GenerateShortLink()
    number_of_active_user=len(User.query.all())
    number_of_active_link=len(Link.query.all())
    context = {"generate":True,"links":number_of_active_link,"users":number_of_active_user}
    if form.validate_on_submit():
        target = form.link.data
        clicked = form.expire.data
        expire_time = time_expire[form.expire_at.data]
        if not flask_login.current_user:
            print('not login')  
            return render_template('index.html',form=form,context=context)     
        while True:
            code = generate_code(8)
            search = Link.query.filter_by(code=code).first()
            if not search:
                clicked = clicked if clicked and clicked > 0 else -1
                link = Link(code=code,target=target,max_clicked=clicked,expire_at=add_time_from_now(expire_time))
                db.session.add(link)    
                db.session.commit()
                context = {"target":target,"code":code,"expire_at":link.expire_at,"generate":False,}             
                break
    return render_template('index.html',form=form,context=context)
        
@main.route("/s/<code_number>")
def redirect_to_tareget(code_number):
    search = Link.query.filter_by(code=code_number).first()
    if (search.expire_at < datetime.utcnow()) or search.max_clicked == search.counter:
        db.session.delete(search)
        db.session.commit()
        return "Expire link or maximum clicked is reached",404

    if search:
        search.counter += 1
        db.session.commit()
        return render_template("redirect.html",target=search.target)


@main.errorhandler(404)
def not_found_error(error):
    return render_template('404.html'), 404

@main.errorhandler(500)
def internal_error(error):
    db.session.rollback()
    return render_template('500.html'), 500

cutlink/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
        {% endblock %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }} ">

        <title>{% block title %} My Webpage {% endblock %} </title>
        {% endblock %}
    </head>
    <body>
    

        <!-- Your page content -->
        {% block content %}{% endblock %}

        {% block scripts %}
            <!-- Optional JavaScript -->
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>


</html>

cutlink/templates/components/create_field_auth.html
{% macro create_field(field) %}

<div class="d-flex flex-row align-items-center mb-4">
  <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
  <div class="form-outline flex-fill mb-0">
    {{ field.label(class='form-label') }}
    {{ field(class='form-control') }}
    <div class="invalid-feedback">
      {% for error in field.errors %}
          <span>{{ error }}</span>
      {% endfor %}
  </div>
  </div>
</div>

{% endmacro %}

cutlink/templates/index.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}


{% block content %}

{% include 'layout/navbar.html' %}

{% if  current_user.is_authenticated %}
    {% if context['generate'] %}
        {% include 'layout/generate.html' %}
    {% else %}
        {% include 'layout/result.html' %}
    {% endif%}
{% else %}
{% include 'layout/info.html' %}
{% endif %}

{% include 'layout/footer.html' %}
{% endblock %}

cutlink/templates/layout/footer.html
<!-- Footer  -->
<footer class="bg-light footer fixed-bottom" >
    <div class="container">
        <div class="row">
            <div class="col-lg-6 text-center text-lg-start my-auto h-100">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item"><a href="#">About</a></li>
                    <li class="list-inline-item"><span>⋅</span></li>
                    <li class="list-inline-item"><a href="#">Contact</a></li>
                    <li class="list-inline-item"><span>⋅</span></li>
                    <li class="list-inline-item"><a href="#">Terms of &nbsp;Use</a></li>
                    <li class="list-inline-item"><span>⋅</span></li>
                    <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">© Brand 2022. All Rights Reserved.</p>
            </div>
            <div class="col-lg-6 text-center text-lg-end my-auto h-100">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item"><a href="#"><i class="fa fa-facebook fa-2x fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-twitter fa-2x fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-instagram fa-2x fa-fw"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

cutlink/templates/layout/generate.html
{% import 'components/create_field_auth.html' as field_creator %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Generate New Link  </p>
  
                  <form class="mx-1 mx-md-4" method="post">
                    {{ form.csrf_token }}
                    {% if form.csrf_token.errors %}
                      <div class="warning">You have submitted an invalid CSRF token</div>
                    {% endif %}

  
                    {{ field_creator.create_field(form.link) }}
                    {{ field_creator.create_field(form.expire) }}
                    {{ field_creator.create_field(form.expire_at) }}

 
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      {{form.submit(class='btn btn-primary btn-lg')}}
                    </div>
  
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                  <img src="{{ url_for('static',filename='media/illustrations/sigma/2.png') }}"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

cutlink/templates/layout/info.html
{% import 'components/create_field_auth.html' as field_creator %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Our Permisions </p>
  

                  <div class="container">

                  <div class="row" style="margin-bottom: 120px;">
                    <div class="col-md-3 col-sm-6">
                    <div class="counter">
                    <div class="counter-icon">
                    <i class="fa fa-globe"></i>
                    </div>
                    <h3>Users</h3>
                    <span class="counter-value">{{ context['users'] }}</span>
                    </div>
                    </div>

                    <div class="col-md-3 col-sm-6" style="margin-left: 100px;">
                    <div class="counter orange">
                    <div class="counter-icon">
                    <i class="fa fa-rocket"></i>
                    </div>
                    <h3>Web Links</h3>
                    <span class="counter-value">{{ context['links'] }}</span>
                    </div>
                    </div>
                    </div>

                  </div>





                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <a href="{{ url_for('auth.login') }}"><div class="btn btn-primary btn-lg" style="margin-left: 25px;"> sign in </div></a>
                    <a href="{{ url_for('auth.register') }}"><div class="btn btn-secondary btn-lg" style="margin-left: 25px;"> sign up </div></a>
                  </div>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                  <img src="{{ url_for('static',filename='media/illustrations/sigma/17.png') }}"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

cutlink/templates/layout/master.html
<!DOCTYPE html>
<html lang="en" >
    <!--begin::Head-->
    <head>
        <title>{% block title %}{% endblock title %} - Keenthemes</title>
        <meta charset="utf-8"/>
        <meta name="description" content=""/>
        <meta name="keywords" content=""/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>      
        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="" />
        <link rel="canonical" href=""/>
        <link rel="shortcut icon" />

        {% block css %}
        <!--begin::Fonts-->
        {{ includeFonts() }}
        <!--end::Fonts-->

        <!--begin::Vendor Stylesheets(optional)-->
        {% for file in getVendors('css') %}
        <link href="{{ file }}" rel="stylesheet" type="text/css" />
        {% endfor %}
        <!--end::Vendor Stylesheets-->

        <!--begin::Custom Stylesheets(optional)-->
        {% for file in getCustomCss() %}
        <link href="{{ url_for('static', filename=file) }}" rel="stylesheet" type="text/css" />
        {% endfor %}
        <!--end::Custom Stylesheets-->

        <!--begin::Global Stylesheets(mandatory)-->
        {% for file in getGlobalAssets('css') %}
        <link href="{{ url_for('static', filename=file) }}" rel="stylesheet" type="text/css" />
        {% endfor %}
        <!--end::Global Stylesheets-->
        {% endblock css %}

        <!--begin::Tracking-->
        <!--end::Tracking-->
    </head>
    <!--end::Head-->

    <!--begin::Body-->
    <body {{ printHtmlClasses('body') }} {{ printHtmlAttributes('body') }}>

        

        {% block layout %}
        {% endblock layout %}

        {% block javascript %}
        <!--begin::Global Javascript(mandatory)-->
        {% for file in getGlobalAssets('js') %}
            <script src="{{ url_for('static', filename=file) }}"></script>
        {% endfor %}
        <!--end::Global Javascript-->

        <!--begin::Vendors Javascript(optional)-->
        {% for file in getVendors('js') %}
        <script src="{{ file }}"></script>
        {% endfor %}
        <!--end::Vendors Javascript-->

        <!--begin::Custom Javascript(optional)-->
        {% for file in getCustomJs() %}
        <script src="{{ url_for('static', filename=file) }}"></script>
        {% endfor %}
        <!--end::Custom Javascript-->
        {% endblock javascript %}

    </body>
    <!--end::Body-->
</html>

cutlink/templates/layout/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-light navbar-expand bg-light navigation-clean fixed-top">
    <div class="container"><a class="navbar-brand" href="#">CUTLINK</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            {% if current_user.is_authenticated %}
            {{current_user.email}}
            <a class="btn btn-primary ms-auto" role="button" href="{{ url_for('auth.logout')}}">Log out</a>
            {% else %}
            <a class="btn btn-primary ms-auto" role="button" href="{{ url_for('auth.login')}}">Sign in</a>
            {% endif %}
        </div>
    </div>
</nav>

cutlink/templates/layout/result.html
{% import 'components/create_field_auth.html' as field_creator %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Congraguation! </p>


                  <div class="form-check d-flex justify-content-center mb-5">
                    <label class="form-check-label" for="form2Example3">
                      Your link expire at {{ context['expire_at'] }} :
                      <a id="link_target" href="{{ url_for('main.redirect_to_tareget',code_number=context['code'])}}">
                        <h3>{{ context['code'] }}</h3>                     
                    </a>
                    <p class="small text-muted">
                      {{ context['target'] }}
                    </p>
                    
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <div onclick="CopyHref('link_target')" class="btn btn-primary btn-lg"> Copy</div>
                    <a href="{{ url_for('main.index') }}"><div class="btn btn-secondary btn-lg" style="margin-left: 25px;"> Next Link </div></a>
                  </div>
    
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                  <img src="{{ url_for('static',filename='media/illustrations/sigma/12.png') }}"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <script>
function CopyToClipboard(containerid) {
  if (document.selection) {
    var range = document.body.createTextRange();
    range.moveToElementText(document.getElementById(containerid));
    range.select().createTextRange();
    document.execCommand("copy");
  } else if (window.getSelection) {
    var range = document.createRange();
    range.selectNode(document.getElementById(containerid));
    window.getSelection().addRange(range);
    document.execCommand("copy");
    // alert("Text has been copied, now paste in the text-area")
  }
}
function CopyHref(containerid){
    var host = window.location.host;
    var copyText = host + document.getElementById(containerid).getAttribute('href');

    var el = document.createElement('textarea');
    el.value = copyText;
    el.setAttribute('readonly', '');
    el.style = {
        position: 'absolute',
        left: '-9999px'
    };
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);

}

  </script>

cutlink/templates/redirect.html
{% extends 'base.html' %}


{% block content %}

<div class="center">
    <h3>
        You should be automatically redirected in <span id="seconds">7</span> seconds.
    </h3>
</div>




<script>
    // Countdown timer for redirecting to another URL after several seconds

    var seconds = 7; // seconds for HTML
    var foo; // variable for clearInterval() function

    function redirect() {
        document.location.href = '{{ target }}';
    }

    function updateSecs() {
        document.getElementById("seconds").innerHTML = seconds;
        seconds--;
        if (seconds == -1) {
            clearInterval(foo);
            redirect();
        }
    }

    function countdownTimer() {
        foo = setInterval(function () {
            updateSecs()
        }, 1000);
    }

    countdownTimer();
</script>

{% endblock %}